"""Embedding spaces: provider, normalisation and semantic text per search document.

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-04

- `embedding_provider` and `embedding_normalized` complete the identity of an embedding space
  (provider, model, dimension, normalisation); vectors are only compared within one space.
- `semantic_text` stores exactly the text that was embedded.
- CHECK `vector_dims(embedding) = embedding_dimension`: the database refuses vectors whose
  length differs from their declared dimension (nothing is ever truncated or padded).

Existing vectors predate provider tracking: they are labelled from their model name and will
be regenerated by the next `index` run (their content hash no longer matches).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLE = "icd_search_documents"


def upgrade() -> None:
    op.add_column(TABLE, sa.Column("semantic_text", sa.Text(), nullable=True))
    op.add_column(TABLE, sa.Column("embedding_provider", sa.String(64), nullable=True))
    op.add_column(TABLE, sa.Column("embedding_normalized", sa.Boolean(), nullable=True))
    op.execute(
        f"UPDATE {TABLE} SET "
        "embedding_provider = CASE WHEN embedding_model LIKE 'hashing%' THEN 'hashing' "
        "ELSE 'legacy' END, embedding_normalized = true "
        "WHERE embedding IS NOT NULL"
    )
    op.create_check_constraint(
        op.f("ck_icd_search_documents_embedding_has_space"),
        TABLE,
        "embedding IS NULL OR (embedding_provider IS NOT NULL "
        "AND embedding_normalized IS NOT NULL)",
    )
    op.create_check_constraint(
        op.f("ck_icd_search_documents_embedding_dimension_matches"),
        TABLE,
        "embedding IS NULL OR vector_dims(embedding) = embedding_dimension",
    )


def downgrade() -> None:
    op.drop_constraint(
        op.f("ck_icd_search_documents_embedding_dimension_matches"), TABLE, type_="check"
    )
    op.drop_constraint(op.f("ck_icd_search_documents_embedding_has_space"), TABLE, type_="check")
    op.drop_column(TABLE, "embedding_normalized")
    op.drop_column(TABLE, "embedding_provider")
    op.drop_column(TABLE, "semantic_text")
